name: export_helper_flutter
version: 0.1.0
publish_to: 'none'
description: Flutter app for exporting media, generating thumbnails, and classifying images with tflite.
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  image: ^4.1.3
  file_picker: ^6.1.1
  shelf: ^1.4.0
  shelf_cors_headers: any
  photo_manager: ^3.8.3
  http: ^1.6.0
